version: "3.9"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=PAD_Cluster
      - CASSANDRA_NUM_TOKENS=8
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  dw1:
    build:
      context: .
      dockerfile: DWServer/Dockerfile
    container_name: dw1
    depends_on:
      - cassandra
    ports:
      - "5128:80"

  dw2:
    build:
      context: .
      dockerfile: DWServer/Dockerfile
    container_name: dw2
    depends_on:
      - cassandra
    ports:
      - "6001:80"

  proxy:
    build:
      context: .
      dockerfile: ProxyServer/Dockerfile
    container_name: proxy
    ports:
      - "8085:8080"
    depends_on:
      - dw1
      - dw2
      - redis
      - cassandra

volumes:
  cassandra_data:
  redis_data:
